### ISSUE TITLE
Redeem GitHub Copilot

### ISSUE THREAD

**Issue by javierrc8** [MVFoulRecognition/MVFoulRecognition#9]
## Description
As the University of Seville has an agreement with Github Copilot, it will be useful to redeem it.

## Additional Context
(https://github.com/education/students)

**Comment by javierrc8** [comment]
We've both asked for it, we are now waiting for response.

**Comment by javierrc8** [comment]
My solicitation has been approved.

**Comment by juamarcan8** [comment]
My solicitation has been approved.
